sudo: false
language: rust
rust:
  - nightly
  - beta
  - 1.12.0

script:
  - cargo test
  - cargo test --features "normalizer_mysql unstable"
  - cargo test --features "normalizer_mysql unstable sharding"
