sudo: false
language: rust
rust:
  - nightly
  - beta
  - 1.13.0

script:
  - cargo test && cargo clean
  - cargo test --features "normalizer_mysql unstable" && cargo clean
  - cargo test --features "normalizer_mysql unstable sharding"
