[package]
name = "ruroonga_command"
version = "0.1.0"
authors = ["Hiroshi Hatake <cosmo0920.oucc@gmail.com>"]
keywords = ["groonga"]
description = "A tiny Groonga query builder and generator."
license-file = "LICENSE"
repository = "https://github.com/cosmo0920/ruroonga_command"
build = "build.rs"

[features]
normalizer_mysql = []
unstable = []

[build-dependencies.skeptic]
version = "~0.4"
default-features = false

[dev-dependencies.skeptic]
version = "~0.4"
default-features = false

[dependencies]
url = "~0.5.2"
