(function() {var implementors = {};
implementors["ruroonga_command"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='ruroonga_command/selectable/drilldown/struct.Drilldown.html' title='ruroonga_command::selectable::drilldown::Drilldown'>Drilldown</a>&gt; for <a class='struct' href='ruroonga_command/select/struct.SelectCommand.html' title='ruroonga_command::select::SelectCommand'>SelectCommand</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='ruroonga_command/selectable/labeled_drilldown/struct.LabeledDrilldown.html' title='ruroonga_command::selectable::labeled_drilldown::LabeledDrilldown'>LabeledDrilldown</a>&gt; for <a class='struct' href='ruroonga_command/select/struct.SelectCommand.html' title='ruroonga_command::select::SelectCommand'>SelectCommand</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html' title='collections::vec::Vec'>Vec</a>&lt;<a class='struct' href='ruroonga_command/selectable/labeled_drilldown/struct.LabeledDrilldown.html' title='ruroonga_command::selectable::labeled_drilldown::LabeledDrilldown'>LabeledDrilldown</a>&gt;&gt; for <a class='struct' href='ruroonga_command/select/struct.SelectCommand.html' title='ruroonga_command::select::SelectCommand'>SelectCommand</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;<a class='struct' href='ruroonga_command/selectable/staged_columns/struct.StagedColumns.html' title='ruroonga_command::selectable::staged_columns::StagedColumns'>StagedColumns</a>&gt; for <a class='struct' href='ruroonga_command/select/struct.SelectCommand.html' title='ruroonga_command::select::SelectCommand'>SelectCommand</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
